version: '2'
services:
  web:
    image: nginx:1.8
    ports:
      - 40080:80
    links:
      - php
    volumes:
      - ./docker/web/conf.d:/etc/nginx/conf.d
    volumes_from:
      - php
  php:
    build: ./docker/php-dev
    links:
      - neo4j
    volumes:
      - ./:/var/www/html/
    environment:
      NEO4J_DEFAULT: 'bolt://neo4j:demo@neo4j'
  neo4j:
    image: neo4j:3.0
    ports:
      - 47474:7474
    volumes:
      - ./storage/neo4j:/data

